
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
exec-once  = hyprpm reload -n
exec-once = coolercontrol
exec-once = steam -silent
exec-once = sunshine


# Keyboard languages
input {
    kb_layout = de, us
}

# Window layout
plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
    wslayout {
        default_layout = dwindle
    }
}

master {
    new_status = inherit  # slave 
    mfact = 0.5
    orientation = center
    slave_count_for_center_master = 0
    new_on_top = true
    # center_master_slaves_on_right = false
}

dwindle {
    single_window_aspect_ratio = 16 9
    # smart_split = true
}

general {
    layout = dwindle
}

# workspace = 1, layoutopt:wslayout-layout:dwindle 
# workspace = 2, layoutopt:wslayout-layout:dwindle 
# workspace = 3, layoutopt:wslayout-layout:dwindle 
# workspace = 4, layoutopt:wslayout-layout:dwindle 
# workspace = 5, layoutopt:wslayout-layout:dwindle 
# workspace = 10, layoutopt:wslayout-layout:dwindle 
# workspace = 11, layoutopt:wslayout-layout:dwindle 
# workspace = 12, layoutopt:wslayout-layout:dwindle 
# workspace = 13, layoutopt:wslayout-layout:dwindle 
# workspace = 14, layoutopt:wslayout-layout:dwindle 
# workspace = 15, layoutopt:wslayout-layout:dwindle 

# Fix Unreal Engine 5 issues
windowrulev2 = noinitialfocus,class:^(UnrealEditor)$,title:^\w*$

# Keybind overrides

# for window shallow similar to devour
misc {
    enable_swallow = true
    swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|WezTerm|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}

# hyprlang endif

