
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

# Keyboard languages
input {
    kb_layout = de, us
}

# Window layout
plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
    wslayout {
        default_layout = master
    }
}

master {
    new_status = inherit  # slave 
    mfact = 0.5
    orientation = center
    slave_count_for_center_master = 0
    new_on_top = true
    # center_master_slaves_on_right = false
}

general {
    layout = workspacelayout
    # layout = master
}

workspace = 5, layoutopt:wslayout-layout:dwindle 
workspace = 6, layoutopt:wslayout-layout:dwindle 
workspace = 7, layoutopt:wslayout-layout:dwindle 
workspace = 8, layoutopt:wslayout-layout:dwindle 
workspace = 9, layoutopt:wslayout-layout:dwindle 
workspace = 10, layoutopt:wslayout-layout:dwindle 

# Fix Unreal Engine 5 issues
windowrulev2 = noinitialfocus,class:^(UnrealEditor)$,title:^\w*$

# Keybind overrides


