
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
exec-once  = hyprpm reload -n
exec-once = protonvpn-app
exec-once = steam -silent
exec-once = coolercontrol
exec-once = sunshine

# Keyboard languages
input {
    kb_layout = de, us
}

# Window layout
plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
    wslayout {
        default_layout = dwindle
    }
}

master {
    new_status = inherit  # slave 
    mfact = 0.5
    orientation = center
    slave_count_for_center_master = 0
    new_on_top = true
    # center_master_slaves_on_right = false
}

layout {
    single_window_aspect_ratio = 16 9
}

dwindle {
    # smart_split = true
}

general {
    layout = dwindle
}

# Fix Unreal Engine 5 issues
windowrule {
    name = unreal-editor-fix
    match:class = UE5Editor

    # Fokus
    no_initial_focus = on
    suppress_event = activate

    # Rendering
    no_anim = on
    no_blur = on
    no_shadow = on
    group = "deny"
    opacity = 1.0 1.0
}

# Keybind overrides

# for window shallow similar to devour
misc {
    enable_swallow = true
    swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|WezTerm|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}


